### ISSUE TITLE
[BUG]: Test

### ISSUE THREAD

**Issue by max-zaytsev** [max-zaytsev/TESTREPO#10]
### New issue checklist

- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)
- [X] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [X] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Issue Description

A bug happened!

### Task name

111

### Task version

111

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Windows

### Task log

```shell
Logs
```

### Relevant log output

```shell
Logs
```
