### ISSUE TITLE
[BUG]: New

### ISSUE THREAD

**Issue by max-zaytsev** [max-zaytsev/TESTREPO#11]
### New issue checklist

- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)
- [ ] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [ ] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Issue Description

A bug happened!

### Task name

11

### Task version

11

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

a

### Task log

```shell
a
```

### Relevant log output

```shell
q
```

## Additional logs:
<details>
```log

 [REPLACE THIS WITH YOUR INFORMATION]

```
</details>
