### ISSUE TITLE
[BUG]: New bug

### ISSUE THREAD

**Issue by max-zaytsev** [max-zaytsev/TESTREPO#12]
### New issue checklist

- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)
- [ ] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [ ] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Issue Description

A bug happened! 1

### Task name

1

### Task version

1

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Win

### Task log

```shell
2023-11-08T15:25:24.6390044Z ##[section]Starting: Deploy Master Website
2023-11-08T15:25:24.8786573Z ==============================================================================
2023-11-08T15:25:24.8786962Z Task         : IIS web app deploy
2023-11-08T15:25:24.8787280Z Description  : Deploy a website or web application using Web Deploy
2023-11-08T15:25:24.8787598Z Version      : 0.230.0
2023-11-08T15:25:24.8787854Z Author       : Microsoft Corporation
2023-11-08T15:25:24.8788273Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/iis-web-app-deployment-on-machine-group
2023-11-08T15:25:24.8788775Z ==============================================================================
2023-11-08T15:25:29.5446503Z [command]"C:\azagent\A2\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-tasks-webdeployment-common\MSDeploy3.6\MSDeploy3.6\msdeploy.exe" -verb:sync -source:package='C:\azagent\A2\_work\r523\a\ Web & All Databases\Web\WebApp.zip' -dest:auto -setParam:name='IIS Web Application Name',value='Default Web Site/Master' -enableRule:DoNotDeleteRule
2023-11-08T15:25:30.2377991Z Error: The process 'C:\azagent\A2\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-tasks-webdeployment-common\MSDeploy3.6\MSDeploy3.6\msdeploy.exe' failed with exit code 1
2023-11-08T15:25:30.2381018Z     at ExecState._setResult (C:\azagent\A2\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-task-lib\toolrunner.js:943:25)
2023-11-08T15:25:30.2403607Z     at ExecState.CheckComplete (C:\azagent\A2\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-task-lib\toolrunner.js:926:18)
2023-11-08T15:25:30.2413425Z     at ChildProcess.<anonymous> (C:\azagent\A2\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-task-lib\toolrunner.js:839:19)
2023-11-08T15:25:30.2426387Z     at ChildProcess.emit (node:events:527:28)
2023-11-08T15:25:30.2430939Z     at maybeClose (node:internal/child_process:1092:16)
2023-11-08T15:25:30.2432266Z     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
2023-11-08T15:25:30.2433519Z     at Process.callbackTrampoline (node:internal/async_hooks:130:17)
2023-11-08T15:25:30.2435088Z Retrying to deploy the package.
2023-11-08T15:25:30.2458513Z [command]"C:\azagent\A2\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-tasks-webdeployment-common\MSDeploy3.6\MSDeploy3.6\msdeploy.exe" -verb:sync -source:package='C:\azagent\A2\_work\r523\a\ Web & All Databases\Web\WebApp.zip' -dest:auto -setParam:name='IIS Web Application Name',value='Default Web Site/Master' -enableRule:DoNotDeleteRule
2023-11-08T15:25:30.9353956Z Error: The process 'C:\azagent\A2\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-tasks-webdeployment-common\MSDeploy3.6\MSDeploy3.6\msdeploy.exe' failed with exit code 1
2023-11-08T15:25:30.9356159Z     at ExecState._setResult (C:\azagent\A2\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-task-lib\toolrunner.js:943:25)
2023-11-08T15:25:30.9357950Z     at ExecState.CheckComplete (C:\azagent\A2\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-task-lib\toolrunner.js:926:18)
2023-11-08T15:25:30.9359539Z     at ChildProcess.<anonymous> (C:\azagent\A2\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-task-lib\toolrunner.js:839:19)
2023-11-08T15:25:30.9361275Z     at ChildProcess.emit (node:events:527:28)
2023-11-08T15:25:30.9361947Z     at maybeClose (node:internal/child_process:1092:16)
2023-11-08T15:25:30.9364818Z     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
2023-11-08T15:25:30.9365676Z     at Process.callbackTrampoline (node:internal/async_hooks:130:17)
2023-11-08T15:25:30.9366295Z Retrying to deploy the package.
2023-11-08T15:25:30.9386202Z [command]"C:\azagent\A2\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-tasks-webdeployment-common\MSDeploy3.6\MSDeploy3.6\msdeploy.exe" -verb:sync -source:package='C:\azagent\A2\_work\r523\a\ Web & All Databases\ Web\WebApp.zip' -dest:auto -setParam:name='IIS Web Application Name',value='Default Web Site/Master' -enableRule:DoNotDeleteRule
2023-11-08T15:25:31.6161495Z ##[error]Failed to deploy web package to IIS website.
2023-11-08T15:25:31.6176104Z ##[error]Error: A '-dest' argument must be specified with the 'sync' verb.
Error count: 1.
'All' is not recognized as an internal or external command,
operable program or batch file.

2023-11-08T15:25:31.7174337Z ##[error]Error: The process 'C:\azagent\A2\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-tasks-webdeployment-common\MSDeploy3.6\MSDeploy3.6\msdeploy.exe' failed with exit code 1
2023-11-08T15:25:31.8731989Z ##[section]Finishing: Deploy Master Website
```

### Relevant log output

```shell
2023-11-08T15:25:24.6390044Z ##[section]Starting: Deploy Master Website
2023-11-08T15:25:24.8786573Z ==============================================================================
2023-11-08T15:25:24.8786962Z Task         : IIS web app deploy
2023-11-08T15:25:24.8787280Z Description  : Deploy a website or web application using Web Deploy
2023-11-08T15:25:24.8787598Z Version      : 0.230.0
2023-11-08T15:25:24.8787854Z Author       : Microsoft Corporation
2023-11-08T15:25:24.8788273Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/iis-web-app-deployment-on-machine-group
2023-11-08T15:25:24.8788775Z ==============================================================================
2023-11-08T15:25:29.5446503Z [command]"C:\azagent\A2\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-tasks-webdeployment-common\MSDeploy3.6\MSDeploy3.6\msdeploy.exe" -verb:sync -source:package='C:\azagent\A2\_work\r523\a\ Web & All Databases\Web\WebApp.zip' -dest:auto -setParam:name='IIS Web Application Name',value='Default Web Site/Master' -enableRule:DoNotDeleteRule
2023-11-08T15:25:30.2377991Z Error: The process 'C:\azagent\A2\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-tasks-webdeployment-common\MSDeploy3.6\MSDeploy3.6\msdeploy.exe' failed with exit code 1
2023-11-08T15:25:30.2381018Z     at ExecState._setResult (C:\azagent\A2\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-task-lib\toolrunner.js:943:25)
2023-11-08T15:25:30.2403607Z     at ExecState.CheckComplete (C:\azagent\A2\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-task-lib\toolrunner.js:926:18)
2023-11-08T15:25:30.2413425Z     at ChildProcess.<anonymous> (C:\azagent\A2\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-task-lib\toolrunner.js:839:19)
2023-11-08T15:25:30.2426387Z     at ChildProcess.emit (node:events:527:28)
2023-11-08T15:25:30.2430939Z     at maybeClose (node:internal/child_process:1092:16)
2023-11-08T15:25:30.2432266Z     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
2023-11-08T15:25:30.2433519Z     at Process.callbackTrampoline (node:internal/async_hooks:130:17)
2023-11-08T15:25:30.2435088Z Retrying to deploy the package.
2023-11-08T15:25:30.2458513Z [command]"C:\azagent\A2\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-tasks-webdeployment-common\MSDeploy3.6\MSDeploy3.6\msdeploy.exe" -verb:sync -source:package='C:\azagent\A2\_work\r523\a\ Web & All Databases\Web\WebApp.zip' -dest:auto -setParam:name='IIS Web Application Name',value='Default Web Site/Master' -enableRule:DoNotDeleteRule
2023-11-08T15:25:30.9353956Z Error: The process 'C:\azagent\A2\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-tasks-webdeployment-common\MSDeploy3.6\MSDeploy3.6\msdeploy.exe' failed with exit code 1
2023-11-08T15:25:30.9356159Z     at ExecState._setResult (C:\azagent\A2\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-task-lib\toolrunner.js:943:25)
2023-11-08T15:25:30.9357950Z     at ExecState.CheckComplete (C:\azagent\A2\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-task-lib\toolrunner.js:926:18)
2023-11-08T15:25:30.9359539Z     at ChildProcess.<anonymous> (C:\azagent\A2\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-task-lib\toolrunner.js:839:19)
2023-11-08T15:25:30.9361275Z     at ChildProcess.emit (node:events:527:28)
2023-11-08T15:25:30.9361947Z     at maybeClose (node:internal/child_process:1092:16)
2023-11-08T15:25:30.9364818Z     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
2023-11-08T15:25:30.9365676Z     at Process.callbackTrampoline (node:internal/async_hooks:130:17)
2023-11-08T15:25:30.9366295Z Retrying to deploy the package.
2023-11-08T15:25:30.9386202Z [command]"C:\azagent\A2\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-tasks-webdeployment-common\MSDeploy3.6\MSDeploy3.6\msdeploy.exe" -verb:sync -source:package='C:\azagent\A2\_work\r523\a\ Web & All Databases\ Web\WebApp.zip' -dest:auto -setParam:name='IIS Web Application Name',value='Default Web Site/Master' -enableRule:DoNotDeleteRule
2023-11-08T15:25:31.6161495Z ##[error]Failed to deploy web package to IIS website.
2023-11-08T15:25:31.6176104Z ##[error]Error: A '-dest' argument must be specified with the 'sync' verb.
Error count: 1.
'All' is not recognized as an internal or external command,
operable program or batch file.

2023-11-08T15:25:31.7174337Z ##[error]Error: The process 'C:\azagent\A2\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-tasks-webdeployment-common\MSDeploy3.6\MSDeploy3.6\msdeploy.exe' failed with exit code 1
2023-11-08T15:25:31.8731989Z ##[section]Finishing: Deploy Master Website
```

### Aditional info

<details>
  <pre> 2023-11-08T15:25:24.6390044Z ##[section]Starting: Deploy Master Website
2023-11-08T15:25:24.8786573Z ==============================================================================
2023-11-08T15:25:24.8786962Z Task         : IIS web app deploy
2023-11-08T15:25:24.8787280Z Description  : Deploy a website or web application using Web Deploy
2023-11-08T15:25:24.8787598Z Version      : 0.230.0
2023-11-08T15:25:24.8787854Z Author       : Microsoft Corporation
2023-11-08T15:25:24.8788273Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/iis-web-app-deployment-on-machine-group
2023-11-08T15:25:24.8788775Z ==============================================================================
2023-11-08T15:25:29.5446503Z [command]"C:\azagent\A2\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-tasks-webdeployment-common\MSDeploy3.6\MSDeploy3.6\msdeploy.exe" -verb:sync -source:package='C:\azagent\A2\_work\r523\a\ Web & All Databases\Web\WebApp.zip' -dest:auto -setParam:name='IIS Web Application Name',value='Default Web Site/Master' -enableRule:DoNotDeleteRule
2023-11-08T15:25:30.2377991Z Error: The process 'C:\azagent\A2\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-tasks-webdeployment-common\MSDeploy3.6\MSDeploy3.6\msdeploy.exe' failed with exit code 1
2023-11-08T15:25:30.2381018Z     at ExecState._setResult (C:\azagent\A2\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-task-lib\toolrunner.js:943:25)
2023-11-08T15:25:30.2403607Z     at ExecState.CheckComplete (C:\azagent\A2\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-task-lib\toolrunner.js:926:18)
2023-11-08T15:25:30.2413425Z     at ChildProcess.<anonymous> (C:\azagent\A2\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-task-lib\toolrunner.js:839:19)
2023-11-08T15:25:30.2426387Z     at ChildProcess.emit (node:events:527:28)
2023-11-08T15:25:30.2430939Z     at maybeClose (node:internal/child_process:1092:16)
2023-11-08T15:25:30.2432266Z     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
2023-11-08T15:25:30.2433519Z     at Process.callbackTrampoline (node:internal/async_hooks:130:17)
2023-11-08T15:25:30.2435088Z Retrying to deploy the package.
2023-11-08T15:25:30.2458513Z [command]"C:\azagent\A2\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-tasks-webdeployment-common\MSDeploy3.6\MSDeploy3.6\msdeploy.exe" -verb:sync -source:package='C:\azagent\A2\_work\r523\a\ Web & All Databases\Web\WebApp.zip' -dest:auto -setParam:name='IIS Web Application Name',value='Default Web Site/Master' -enableRule:DoNotDeleteRule
2023-11-08T15:25:30.9353956Z Error: The process 'C:\azagent\A2\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-tasks-webdeployment-common\MSDeploy3.6\MSDeploy3.6\msdeploy.exe' failed with exit code 1
2023-11-08T15:25:30.9356159Z     at ExecState._setResult (C:\azagent\A2\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-task-lib\toolrunner.js:943:25)
2023-11-08T15:25:30.9357950Z     at ExecState.CheckComplete (C:\azagent\A2\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-task-lib\toolrunner.js:926:18)
2023-11-08T15:25:30.9359539Z     at ChildProcess.<anonymous> (C:\azagent\A2\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-task-lib\toolrunner.js:839:19)
2023-11-08T15:25:30.9361275Z     at ChildProcess.emit (node:events:527:28)
2023-11-08T15:25:30.9361947Z     at maybeClose (node:internal/child_process:1092:16)
2023-11-08T15:25:30.9364818Z     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
2023-11-08T15:25:30.9365676Z     at Process.callbackTrampoline (node:internal/async_hooks:130:17)
2023-11-08T15:25:30.9366295Z Retrying to deploy the package.
2023-11-08T15:25:30.9386202Z [command]"C:\azagent\A2\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-tasks-webdeployment-common\MSDeploy3.6\MSDeploy3.6\msdeploy.exe" -verb:sync -source:package='C:\azagent\A2\_work\r523\a\ Web & All Databases\ Web\WebApp.zip' -dest:auto -setParam:name='IIS Web Application Name',value='Default Web Site/Master' -enableRule:DoNotDeleteRule
2023-11-08T15:25:31.6161495Z ##[error]Failed to deploy web package to IIS website.
2023-11-08T15:25:31.6176104Z ##[error]Error: A '-dest' argument must be specified with the 'sync' verb.
Error count: 1.
'All' is not recognized as an internal or external command,
operable program or batch file.

2023-11-08T15:25:31.7174337Z ##[error]Error: The process 'C:\azagent\A2\_work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba\0.230.0\node_modules\azure-pipelines-tasks-webdeployment-common\MSDeploy3.6\MSDeploy3.6\msdeploy.exe' failed with exit code 1
2023-11-08T15:25:31.8731989Z ##[section]Finishing: Deploy Master Website </pre>
</details>
