### ISSUE TITLE
[BUG]: 1

### ISSUE THREAD

**Issue by max-zaytsev** [max-zaytsev/TESTREPO#13]
### New issue checklist

- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)
- [ ] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [ ] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Issue Description

A bug happened!

### Task name

1

### Task version

1

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Azure DevOps Server Version (if applicable)

s

### Operation system

s

### Task log

```shell
s
```

### Relevant log output

```shell
s
```

### Aditional info

<details>
```log
log
```
</details>
