### ISSUE TITLE
[REGRESSION]: Regression in bash

### ISSUE THREAD

**Issue by max-zaytsev** [max-zaytsev/TESTREPO#16]
### New issue checklist

- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)
- [X] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [X] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

Bash

### Breaking task version

1

### Last working task version

2

### Regression Description

A regression happened!

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Azure DevOps Server Version (if applicable)

1

### Operation system

Win

### Relevant log output

```shell
Log
```

### Full task logs with system.debug enabled

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>
